webtalk_init -webtalk_dir P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 21 22:03:27 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210387038_174145948_180497062_666" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2840324c-ad7c-47c7-85bf-588c7d2d14db" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8c0da72728544b8a9865fae7ef12569a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "256 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "13 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "153" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "28" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "4.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "84380_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3399160918 -regid "210387038_174145948_180497062_666" -xml P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.xml -html P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.html -wdm P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
