webtalk_init -webtalk_dir P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 23 01:30:33 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210387038_174145948_180497062_666" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "07414012-8ba5-4e11-9b79-c5dc78dc026b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8c0da72728544b8a9865fae7ef12569a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "143" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "206 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "16808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4212839486 -regid "210387038_174145948_180497062_666" -xml P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.xml -html P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.html -wdm P:/Desktop/RISC-V_CPU_Extended/RV32i/RV32i.sim/sim_1/behav/xsim/xsim.dir/Top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
